ispiti/racunarstvo/20220209/myimgur/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('sign-up', views.SignUpView.as_view(),name = 'signup'),
]

ispiti/racunarstvo/20220209/myimgur/app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:image_id>/', views.detail, name='detail'),
    path('<int:image_id>/comment', views.comment, name='comment'),
    path('<int:image_id>/like_comment/<int:comment_id>', views.likebtn, name = 'likebtn'),
    path('<int:comment_id>/approve' ,views.approve, name = 'approve'),
    path('<int:image_id>/upvote', views.upvote, name='upvote'),
    path('<int:image_id>/downvote', views.downvote, name='downvote'),
    path('new', views.create_image, name="create_image"),
    path('<int:image_id>/edit', views.update_image, name="edit_image"),
    path('<int:image_id>/delete', views.delete_image, name="delete_image"),
    
]

ispiti/racunarstvo/20220209/myimgur/imgur/urls.py
from django import contrib
from django import urls
from django.contrib import admin
from django.urls import include,path
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('images/', include('app.urls')),
    path('', views.index, name='index'), 
]

ispiti/racunarstvo/20220209/myimgur/app/templates/app/base.html
{% load static %}
<html>
  <head>
    <title>My Lame Imgur</title>


    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet"/>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"></script>

    {% block extrahead %}
    {% endblock %}

    <link rel="stylesheet" href="{% static 'app/css/app.css' %}">
  </head>
  <body>
    <div class="page-header">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">My Lame Imgur</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">
            
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="#">Hi {{ user.username }}!</a>
            </li>
              {% if user.is_superuser %}
              <li class="nav-item">
                <a class="nav-link" href="/admin">Admin Dashboard</a>
              </li>
              {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}    
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>           
            
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
            </li> 
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>
    <div class="content container">
      <div class="row">
        <div class="col-md-12">
          <div class="jumbotron fluid-jumbotron">
            <div class="container">
              <h1 class="display-4">My Lame Imgur</h1>
              <p class="lead">Your one stop place for posting your lamest images!</p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

ispiti/racunarstvo/20220209/myimgur/app/templates/app/create_image.html
{% extends 'app/base.html' %}
{% block extrahead %}
{{ form.media }}
{% endblock extrahead %}
{% block content %}
{% if user.is_authenticated %}
<div class="row">
        <div class="col-md-12">
        {% if action == "create" %}
        <h2 class="text-center">Submit new image</h2>
        {% else %}
        <h2 class="text-center">Edit image</h2>
        {% endif %}
        </div>
    </div>
        
    <form method="post" accept-charset="utf-8">
        {% csrf_token   %}
        {% include 'includes/bs4_form.html' with form=form %}
        <div class="row">
            <div class="col-md-8 mx-auto">
                <input type="submit" value="Submit" class="btn btn-primary">
            </div>
        </div>
            
    </form>
    
    {% else %}
    <div class="row">
        <div class="col-md-12">
        <h2 class="text-center">You are not allowed to create a image, you must sign up first</h2>
        </div>
    </div>
    {% endif %}
{% endblock content %}

ispiti/racunarstvo/20220209/myimgur/app/templates/app/detail.html
{% extends 'app/base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="date">
        {{ image.pub_date }}
      </div>
      {% include "includes/vote_buttons.html" with image=image vote=vote %}
      <h2>{{ image.title }}</h2>
      <img class="app-fit" src="{{image.url}}" alt=""/>
    </div>
    <div class="col-md-6">
      <h3>Description</h3>
      <p>{{ image.description|linebreaksbr }}</p>
      <h3>Comments</h3>
      {% for comment in comments %}
        <div class="border comment">
          
          <p class="red">
            Author: {{ comment.author }} ({{comment.created_at}})
          </p>
          <p class="secondary">
            {{ comment.text }}
          </p>
          {% if user.is_authenticated %}
          <form action="{% url 'app:likebtn' comment_id=comment.id image_id=image.id %}" method="post" class="">
            {% csrf_token %}
            <input class = "btn btn-lg btn-primary" type="submit" value="Like">
            </form>
            <label>{{ comment.like_score }}</label>
          {% endif %}
          {% if user.is_superuser and not comment.is_approved %}
          <form action="{% url 'app:approve' comment.id %}" method="post" class="">
          {% csrf_token %}
          <input class = "btn btn-lg" type="submit" value="Approve comment">
          </form>
          {% endif %}
        </div>
      {% endfor %}

      {% if user.is_authenticated %}
      <h2>Post a comment</h2>
      {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

      <form action="{% url 'app:comment' image.id %}" method="post" class="border">
        {% csrf_token %}
        {% include "includes/bs4_form.html" with form=form %}
        <input type="submit" value="Post Comment" class="btn btn-lg btn-primary btn-block"/>
      </form>
      {% endif %}

      
    </div>
  </div>
</div>
{% endblock %}

ispiti/racunarstvo/20220209/myimgur/app/templates/app/index.html
{% extends 'app/base.html' %}

{% block content %}
    <div class="row">
      <div class="col-md-10">
      {% if user.is_authenticated %}
        <p><a href="{% url 'app:create_image' %}">Submit new image</a></p>
      {% endif %}
      </div>
    </div>
    {% for image,vote in images_with_votes %}
      
        <div class="row">
          <div class="col-md-2">
            <img class="app-fit" src="{{image.url}}" alt=""/>
          </div>
          <div class="col-md-10">
            <div class="date">
              <p class="red">
              Published: {{ image.pub_date }}; Author: {{ image.user.username }};  Comments: {{ image.comment_set.count }}; 
              {% if user == image.user or user.is_superuser %}
                <a href="{% url 'app:edit_image' image.id %}">Edit</a> | 
                {% include "includes/delete_image_link.html" with image=image %}
              {% endif %}
              </p>
            </div>
            {% include "includes/vote_buttons.html" with image=image vote=vote %}
            <h2><a href="{% url 'app:detail' image.id %}">{{ image.title }}</a></h2>
            <p>{{ image.description|linebreaksbr }}</p>
          </div>
        </div>
    {% endfor %}
{% endblock %}