ispiti/racunarstvo/20220129a/myimgur/app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:image_id>/', views.detail, name='detail'),
    path('<int:image_id>/comment', views.comment, name='comment'),
    path('<int:image_id>/like_comment/<int:comment_id>', views.likebtn, name = 'likebtn'),
    path('<int:comment_id>/approve' ,views.approve, name = 'approve'),
    path('<int:image_id>/upvote', views.upvote, name='upvote'),
    path('<int:image_id>/downvote', views.downvote, name='downvote'),
    path('new', views.create_image, name="create_image"),
    path('random', views.random_image, name="random_image"),
    path('<int:image_id>/edit', views.update_image, name="edit_image"),
    path('<int:image_id>/delete', views.delete_image, name="delete_image"),
    
]

ispiti/racunarstvo/20220129a/myimgur/app/views.py
from typing import Text
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Image, Comment, Vote, Like
from .forms import CommentForm, ImageForm
import random

# Create your views here.

def index(request):
    images = Image.objects.order_by('-pub_date')
    votes = [ image.vote_by(request.user) for image in images ]
    context = { 'images_with_votes': zip(images, votes) }
    return render(request, 'app/index.html', context)

def detail(request, image_id):
    image = get_object_or_404(Image,pk=image_id)
    if request.user.is_superuser:
        context = {'image': image, 
                    'vote': image.vote_by(request.user),
                    'comments': image.comment_set.all(),
                    'form': CommentForm(),
                }
    else:
        context = {'image': image, 
                    'vote': image.vote_by(request.user),
                    'comments': image.comment_set.filter(approved=True),
                    'form': CommentForm(),
                }
    return render(request, 'app/detail.html', context)

def create_image(request):
    if request.method == 'POST' and request.user.is_authenticated:
        form = ImageForm(request.POST)
        if form.is_valid():
            saved_image = form.save(commit=False)
            saved_image.user = request.user
            saved_image.save()
            return HttpResponseRedirect(reverse('app:detail', args=(saved_image.id,)))
    else:
        form = ImageForm()
    context = { 'form':form, 'action':'create'}
    return render(request, 'app/create_image.html', context)

def delete_image(request, image_id):
    image = get_object_or_404(Image, pk=image_id)
    if request.method=='POST' and (image.user == request.user or request.user.is_superuser):
        image.delete()
    return HttpResponseRedirect(reverse('app:index'))

def update_image(request, image_id):
    image = get_object_or_404(Image, pk=image_id)
    if request.method == 'POST' and (image.user == request.user or request.user.is_superuser):
        form = ImageForm(request.POST, instance = image)
        if form.is_valid():
            saved_image = form.save()
            return HttpResponseRedirect(reverse('app:detail', args=(saved_image.id,)))
    else:
        form = ImageForm(instance=image)
    context = { 'form':form, 'action':'update'}
    return render(request, 'app/create_image.html', context)

def random_image(request):
    image = random.choice( Image.objects.all() )
    return HttpResponseRedirect(reverse('app:detail', args=(image.id,)))

def comment(request, image_id):
    if request.method == 'POST' and request.user.is_authenticated:
        image = get_object_or_404(Image, pk=image_id)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.image = image
            comment.user = request.user
            comment.save()
            return HttpResponseRedirect(reverse('app:detail',
            args=(comment.image.id,)))
        else:
            return render(request, 'app/detail.html', {
                'image': image,
                'comments' : image.comment_set.all(),
                'form': form,
            })
    else:
        return HttpResponseRedirect(reverse('app:detail', args=(
            image_id,
        )))
def approve(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == 'POST' and request.user.is_superuser:         
        comment.approve()
    return HttpResponseRedirect(reverse('app:detail', args=(comment.image.id,)))

def vote(request, image_id, upvote):
    image = get_object_or_404(Image, pk=image_id)
    vote= Vote.objects.filter(user=request.user, image=image).first()
    if vote:
        if vote.upvote == upvote:
            vote.delete()
            return None
        else:
            vote.upvote = upvote
    else:
        vote= Vote(user=request.user, image=image, upvote=upvote)
        try:
            vote.full_clean()
            vote.save()
        except:
            return None
        else:
            return vote

def upvote(request, image_id):
    if request.method == 'POST' and request.user.is_authenticated:
        vote(request, image_id, True)
    return HttpResponseRedirect(reverse('app:detail', args=(image_id,)))

def downvote(request, image_id):
    if request.method == 'POST' and request.user.is_authenticated:
        vote(request, image_id, False)
    return HttpResponseRedirect(reverse('app:detail', args=(image_id,)))

def like(request, comment_id, likestatus):
    comment = get_object_or_404(Comment, pk=comment_id)
    likecomm= Like.objects.filter(user=request.user, comment=comment).first()
    if likecomm:
        if likecomm.likecomment == likestatus:
            likecomm.delete()
            return None
        else:
            likecomm.likecomment=likestatus
    else:
        likecomm = Like(user=request.user, comment=comment, likecomment = likestatus)
        try:
            likecomm.full_clean()
            likecomm.save()
        except Exception as e:
            print(e)
            return None
        else:
            return likecomm

def likebtn(request, comment_id, image_id):
    if request.method == 'POST' and request.user.is_authenticated:
        like(request, comment_id, True)
    return HttpResponseRedirect(reverse('app:detail', args=(image_id,)))

ispiti/racunarstvo/20220129a/myimgur/app/templates/app/base.html
{% load static %}
<html>
  <head>
    <title>My Lame Imgur</title>


    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet"/>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"></script>

    {% block extrahead %}
    {% endblock %}

    <link rel="stylesheet" href="{% static 'app/css/app.css' %}">
  </head>
  <body>
    <div class="page-header">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">My Lame Imgur</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>

          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'app:random_image' %}"> Random <span class="sr-only">(current)</span></a>
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">
            
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="#">Hi {{ user.username }}!</a>
            </li>
            {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link" href="/admin">Admin Dashboard</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}    
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>           
            
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
            </li> 
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>
    <div class="content container">
      <div class="row">
        <div class="col-md-12">
          <div class="jumbotron fluid-jumbotron">
            <div class="container">
              <h1 class="display-4">My Lame Imgur</h1>
              <p class="lead">Your one stop place for posting your lamest images!</p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

ispiti/racunarstvo/20220129a/myimgur/app/templates/app/index.html
{% extends 'app/base.html' %}

{% block content %}
    <div class="row">
      <div class="col-md-10">
      {% if user.is_authenticated %}
        <p><a href="{% url 'app:create_image' %}">Submit new image</a></p>
      {% endif %}
      </div>
    </div>
    {% for image,vote in images_with_votes %}
      
        <div class="row">
          <div class="col-md-2">
            <img class="app-fit" src="{{image.url}}" alt=""/>
          </div>
          <div class="col-md-10">
            <div class="date">
              <p class="red">
              Published: {{ image.pub_date }}; 
              
              {% if image.user.is_superuser %} 
              <span style="font-weight: bold; color: blue">By: {{ image.user.username }};</span> 
              
              {% else %} 
              <span style="color: black">By: {{ image.user.username }};</span> 
              {% endif %} 
              
              Comments: {{ image.comment_set.count }}; 

              {% if user == image.user or user.is_superuser %}
                <a href="{% url 'app:edit_image' image.id %}"> Edit </a> | 
                {% include "includes/delete_image_link.html" with image=image %}
              {% endif %}
              
              </p>
            </div>
            {% include "includes/vote_buttons.html" with image=image vote=vote %}
            <h2><a href="{% url 'app:detail' image.id %}">{{ image.title }}</a></h2>
            <p>{{ image.description|linebreaksbr }}</p>
          </div>
        </div>
    {% endfor %}
{% endblock %}